CREATE TABLE TXN_MESSAGE (
    id VARCHAR2(24) NOT NULL,
    create_time DATE NOT NULL,
    update_time DATE NOT NULL,
    message_key VARCHAR2(128) NOT NULL,
    producer_code VARCHAR2(64) NOT NULL,
    mq_type VARCHAR2(32) NOT NULL,
    destination VARCHAR2(256) NOT NULL,
    route VARCHAR2(256) NULL,
    sharding_key VARCHAR2(128) NULL,
    payload_text CLOB NOT NULL,
    headers_json CLOB NOT NULL,
    biz_key VARCHAR2(128) NULL,
    message_status VARCHAR2(32) NOT NULL,
    next_dispatch_time DATE NULL,
    parent_id VARCHAR2(24) NULL,
    root_id VARCHAR2(24) NULL,
    dispatch_owner VARCHAR2(128) NULL,
    dispatch_token VARCHAR2(24) NULL,
    dispatch_expire_time DATE NULL,
    CONSTRAINT PK_TXN_MESSAGE PRIMARY KEY (id)
);

CREATE TABLE TXN_MESSAGE_HISTORY (
    id VARCHAR2(24) NOT NULL,
    create_time DATE NOT NULL,
    update_time DATE NOT NULL,
    message_key VARCHAR2(128) NOT NULL,
    producer_code VARCHAR2(64) NOT NULL,
    mq_type VARCHAR2(32) NOT NULL,
    destination VARCHAR2(256) NOT NULL,
    route VARCHAR2(256) NULL,
    sharding_key VARCHAR2(128) NULL,
    payload_text CLOB NOT NULL,
    headers_json CLOB NOT NULL,
    biz_key VARCHAR2(128) NULL,
    message_status VARCHAR2(32) NOT NULL,
    next_dispatch_time DATE NULL,
    parent_id VARCHAR2(24) NULL,
    root_id VARCHAR2(24) NULL,
    dispatch_owner VARCHAR2(128) NULL,
    dispatch_token VARCHAR2(24) NULL,
    dispatch_expire_time DATE NULL,
    CONSTRAINT PK_TXN_MESSAGE_HISTORY PRIMARY KEY (id)
);

CREATE TABLE TXN_CONSUMED_MESSAGE (
    id VARCHAR2(24) NOT NULL,
    create_time DATE NOT NULL,
    update_time DATE NOT NULL,
    message_key VARCHAR2(128) NOT NULL,
    consumer_code VARCHAR2(64) NOT NULL,
    biz_key VARCHAR2(128) NULL,
    consume_status VARCHAR2(32) NOT NULL,
    consume_time DATE NOT NULL,
    CONSTRAINT PK_TXN_CONSUMED_MESSAGE PRIMARY KEY (id),
    CONSTRAINT UK_TXN_CONSUMED_MESSAGE UNIQUE (id, consumer_code)
);

CREATE TABLE TXN_CONSUMED_MESSAGE_HISTORY (
    id VARCHAR2(24) NOT NULL,
    create_time DATE NOT NULL,
    update_time DATE NOT NULL,
    message_key VARCHAR2(128) NOT NULL,
    consumer_code VARCHAR2(64) NOT NULL,
    biz_key VARCHAR2(128) NULL,
    consume_status VARCHAR2(32) NOT NULL,
    consume_time DATE NOT NULL,
    archive_time DATE NOT NULL,
    CONSTRAINT PK_TXN_CONSUMED_MESSAGE_HISTORY PRIMARY KEY (id),
    CONSTRAINT UK_TXN_CONSUMED_MESSAGE_HISTORY UNIQUE (id, consumer_code)
);

CREATE TABLE TXN_MESSAGE_SEND_LOG (
    id VARCHAR2(24) NOT NULL,
    create_time DATE NOT NULL,
    update_time DATE NOT NULL,
    message_key VARCHAR2(128) NOT NULL,
    parent_id VARCHAR2(24) NULL,
    root_id VARCHAR2(24) NULL,
    producer_code VARCHAR2(64) NOT NULL,
    mq_type VARCHAR2(32) NOT NULL,
    send_status VARCHAR2(32) NOT NULL,
    retry_count NUMBER(10) NOT NULL,
    last_send_time DATE NOT NULL,
    description VARCHAR2(512) NULL,
    CONSTRAINT PK_TXN_MESSAGE_SEND_LOG PRIMARY KEY (id)
);

CREATE INDEX IDX_TXN_MESSAGE_STATUS_DISPATCH ON TXN_MESSAGE (message_status, next_dispatch_time, id);
CREATE INDEX IDX_TXN_MESSAGE_STATUS_UPDATE ON TXN_MESSAGE (message_status, update_time, id);

COMMENT ON TABLE TXN_MESSAGE IS '事务消息表';
COMMENT ON COLUMN TXN_MESSAGE.id IS '主键';
COMMENT ON COLUMN TXN_MESSAGE.create_time IS '创建时间';
COMMENT ON COLUMN TXN_MESSAGE.update_time IS '更新时间';
COMMENT ON COLUMN TXN_MESSAGE.message_key IS '消息键';
COMMENT ON COLUMN TXN_MESSAGE.producer_code IS '生产者编码';
COMMENT ON COLUMN TXN_MESSAGE.mq_type IS 'MQ 类型';
COMMENT ON COLUMN TXN_MESSAGE.destination IS '目标';
COMMENT ON COLUMN TXN_MESSAGE.route IS '路由信息';
COMMENT ON COLUMN TXN_MESSAGE.sharding_key IS '分片键';
COMMENT ON COLUMN TXN_MESSAGE.payload_text IS '消息体文本';
COMMENT ON COLUMN TXN_MESSAGE.headers_json IS '消息头 JSON';
COMMENT ON COLUMN TXN_MESSAGE.biz_key IS '业务键';
COMMENT ON COLUMN TXN_MESSAGE.message_status IS '消息状态';
COMMENT ON COLUMN TXN_MESSAGE.next_dispatch_time IS '下次派发时间';
COMMENT ON COLUMN TXN_MESSAGE.parent_id IS '父消息id';
COMMENT ON COLUMN TXN_MESSAGE.root_id IS '根消息id';
COMMENT ON COLUMN TXN_MESSAGE.dispatch_owner IS '派发实例标识';
COMMENT ON COLUMN TXN_MESSAGE.dispatch_token IS '派发令牌';
COMMENT ON COLUMN TXN_MESSAGE.dispatch_expire_time IS '派发租约过期时间';

COMMENT ON TABLE TXN_MESSAGE_HISTORY IS '事务消息历史表';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.id IS '主键';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.create_time IS '创建时间';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.update_time IS '更新时间';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.message_key IS '消息键';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.producer_code IS '生产者编码';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.mq_type IS 'MQ 类型';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.destination IS '目标';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.route IS '路由信息';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.sharding_key IS '分片键';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.payload_text IS '消息体文本';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.headers_json IS '消息头 JSON';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.biz_key IS '业务键';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.message_status IS '消息状态';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.next_dispatch_time IS '下次派发时间';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.parent_id IS '父消息id';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.root_id IS '根消息id';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.dispatch_owner IS '派发实例标识';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.dispatch_token IS '派发令牌';
COMMENT ON COLUMN TXN_MESSAGE_HISTORY.dispatch_expire_time IS '派发租约过期时间';

COMMENT ON TABLE TXN_CONSUMED_MESSAGE IS '已消费消息主表';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.id IS '主键';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.create_time IS '创建时间';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.update_time IS '更新时间';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.message_key IS '消息键';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.consumer_code IS '消费者编码';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.biz_key IS '业务键';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.consume_status IS '消费状态';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE.consume_time IS '消费时间';

COMMENT ON TABLE TXN_CONSUMED_MESSAGE_HISTORY IS '已消费消息历史表';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.id IS '主键';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.create_time IS '创建时间';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.update_time IS '更新时间';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.message_key IS '消息键';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.consumer_code IS '消费者编码';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.biz_key IS '业务键';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.consume_status IS '消费状态';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.consume_time IS '消费时间';
COMMENT ON COLUMN TXN_CONSUMED_MESSAGE_HISTORY.archive_time IS '归档时间';

COMMENT ON TABLE TXN_MESSAGE_SEND_LOG IS '消息发送日志表';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.id IS '主键';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.create_time IS '创建时间';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.update_time IS '更新时间';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.message_key IS '消息键';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.parent_id IS '父消息id';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.root_id IS '根消息id';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.producer_code IS '生产者编码';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.mq_type IS 'MQ 类型';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.send_status IS '发送状态';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.retry_count IS '重试次数';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.last_send_time IS '最后发送时间';
COMMENT ON COLUMN TXN_MESSAGE_SEND_LOG.description IS '结果描述';
